services:
  - type: web
    name: wanderlust-manan
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /listings
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: ATLASDB_URL
        sync: false
      - key: SECRET
        sync: false
